package cpn

import "time"

// ChannelType identifies the external channel through which a user session originates.
type ChannelType string

const (
	// ChannelWeb represents a web browser session.
	ChannelWeb ChannelType = "web"

	// ChannelWhatsApp represents a WhatsApp messaging session.
	ChannelWhatsApp ChannelType = "whatsapp"

	// ChannelTelegram represents a Telegram messaging session.
	ChannelTelegram ChannelType = "telegram"
)

// MessageRole identifies the sender of a message within a session.
type MessageRole string

const (
	// RoleUser indicates the message was sent by a human user.
	RoleUser MessageRole = "user"

	// RoleAssistant indicates the message was generated by the CPN.
	RoleAssistant MessageRole = "assistant"

	// RoleObserver indicates the message was generated by an observer transition.
	RoleObserver MessageRole = "observer"
)

// StreamChunk represents a single chunk of an LLM streaming response,
// delivered to the session for real-time display.
type StreamChunk struct {
	// SessionID links this chunk to a user session.
	SessionID string

	// CPNID identifies the CPN instance producing the stream.
	CPNID string

	// CPNRole is the role label of the producing CPN.
	CPNRole string

	// Content is the text content of this chunk.
	Content string

	// Done indicates whether this is the final chunk in the stream.
	Done bool
}

// Message represents a single message in the session conversation history.
type Message struct {
	// ID uniquely identifies this message.
	ID string

	// Role identifies the sender of this message.
	Role MessageRole

	// Content is the text content of the message.
	Content string

	// CPNID identifies the CPN instance that produced this message.
	CPNID string

	// CPNRole is the role label of the producing CPN.
	CPNRole string

	// CPNDepth is the depth of the producing CPN.
	CPNDepth int

	// Timestamp records when this message was created.
	Timestamp time.Time
}

// HITLAction classifies the human response to a HITL request.
type HITLAction string

const (
	// HITLApprove indicates the human approved the proposed action.
	HITLApprove HITLAction = "approve"

	// HITLReject indicates the human rejected the proposed action.
	HITLReject HITLAction = "reject"

	// HITLRevise indicates the human provided revised input.
	HITLRevise HITLAction = "revise"
)

// HITLResponse carries the human's response to a HITL request.
type HITLResponse struct {
	// Action is the human's decision: approve, reject, or revise.
	Action HITLAction

	// Content carries revised input when Action == HITLRevise.
	// Empty for approve and reject actions.
	Content string
}
