// Code generated by mockery v2.53.6. DO NOT EDIT.

package outputmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HealthRepository is an autogenerated mock type for the HealthRepository type
type HealthRepository struct {
	mock.Mock
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *HealthRepository) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHealthRepository creates a new instance of HealthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthRepository {
	mock := &HealthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
