package persist

import (
	"context"
	"time"
)

// MutationRecord is the persisted audit record for a single topology mutation attempt.
type MutationRecord struct {
	ID             string
	CPNID          string
	SessionID      string
	MutationKind   string
	RequestedBy    string
	Reason         string
	Approved       bool
	RejectedReason string
	AppliedAt      time.Time
}

// MutationRepository is the port for persisting and querying topology mutation records (GAP-7 REQ-005).
type MutationRepository interface {
	// Insert persists a mutation record. ID is generated by the caller or the store.
	Insert(ctx context.Context, r *MutationRecord) error
	// ListByCPN returns all mutation records for a given CPN ID, ordered by AppliedAt desc.
	ListByCPN(ctx context.Context, cpnID string) ([]*MutationRecord, error)
}
