global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "jaeger-spm"
    static_configs:
      - targets: ["jaeger:8889"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "calls_total|duration_milliseconds_bucket|duration_milliseconds_count|duration_milliseconds_sum"
        action: keep

  - job_name: "jaeger-self-monitoring"
    static_configs:
      - targets: ["jaeger:8888"]
